### ISSUE TITLE
Hey pops... (issue with sharing updated tuts regardless of your permission to do so, just a heads up!!!!!)

### ISSUE THREAD

**Issue by ic-myXMB** [vintagedaddyo/MyBB_Tutorials_Archive#1]
Apparently I am getting censored on the community forums when I shared the 2 font awesome fa5 and fa6 forum icons tutorials you gave me permission to update and share. In saying that, I can now see exactly the kind of things you must have went through before leaving the community after contributing so much over the many years, but, just in this little horrific experience I had now with the likes of such folks currently abusing their power I can only imagine what all you went through before finally saying farewell, sadly. Regardless, as such I will not be updating and sharing any of that folder of like 25 tutorials you had given me permission to update and release, sorry, but hopefully you understand and while I know you don't use mybb anymore and haven't in along time I felt I should let you know and tell you that I can send you that directory of such tutorials you gave to me back if you feel like ever updating them and re-releasing the rest of them here if and or when you ever feel like it, and you health improves but I doubt that you should bother with the headaches as is understandable. Call me, let me know. Take care daddyo.

**Comment by vintagedaddyo** [comment]
What?!!! You got to be kidding me?!! Let me guess, was it that antagonistic lil prick omar? Or was it effone? As those are the two that constantly started drama and abused their positions and  power to keep messing with me and antagonized me to all ends for no reason other than to proper c-bags. Regardless kiddo, I hear you. Sorry you went through such because of me as that is unfair to say the least and you know what?! F the lot of them lad, I told them just as much when I left that now piss poor excuse for what was once a true image of beauty and quality of a community that Chris once so lovingly created when forking XMB onwards to the much loved product that came to be over the years and many of us had loved such and the community and its members and cherished such for years and years hence entirely why many spent so much time giving back to such because of such only to then have some kiddos now in power these last few years piss all over everything given and everything loved and cherished. No biggie and simply just understand with a grain of salt lad that it is those types that have slowly destroyed the community while watching so many valued long time contributors walk away in disgust while these clowns appear oblivious to the consequences of their actions and that they themselves are majorly responsible for the massive decline while slowly but surely destroying the community interest.

**Comment by vintagedaddyo** [comment]
just reread and noticed you asked me to call. Assuming since it is the holidays of course I can call you and as such will ring yer mum. It is 3:10 here now so will make sure to call you around 10 your time

**Comment by ic-myXMB** [comment]
k. Let me know if you want the updated ones I published (I only did the two so far, FA Icons ones oh and one brand new tutorial based on how you did the mycomm default theme years ago as a quick support request because some user mentioned your old theme in the request but I did such tut with the newer top menu you never got around to in that old release, oh, and I wrote on my own accord just 2 FA versions tutorials starting from your comment a few years ago on that preloader tut, that is all before the drama happened, sorry, let me know)
